version: "3"

networks:
  app_net:

services:
  app:
    container_name: app
    image: chenks/paste-bin:latest
    networks:
      - app_net
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - BIND=0.0.0.0:8080
      - REDIS=redis://redis:6379
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis:6-alpine
    networks:
      - app_net
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 2s
      timeout: 20s
      retries: 30
